hospitalmanagement/urls.py
from django.contrib import admin
from django.urls import path
from hospital.views import admin_views, doctor_views, patient_views,feature_views,authentication_views,common_views,appointment_views,misc_views,report_views
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("user_login/", authentication_views.user_login, name="user_login"),
    path('afterlogin', authentication_views.afterlogin_view,name='afterlogin'),
    path('adminlogin', LoginView.as_view(template_name='hospital/adminlogin.html')),
    path('doctorlogin', LoginView.as_view(template_name='hospital/doctorlogin.html')),
    path('patientlogin', LoginView.as_view(template_name='hospital/patientlogin.html')),
    path('logout', authentication_views.logout_view,name='logout'),
    path('delete-doctor-from-hospital/<int:pk>', misc_views.delete_doctor_from_hospital_view,name='delete-doctor-from-hospital'),
    path('approve-doctor/<int:pk>', appointment_views.approve_doctor_view,name='approve-doctor'),
    path('reject-doctor/<int:pk>', appointment_views.reject_doctor_view,name='reject-doctor'),
    path('approve-patient/<int:pk>', appointment_views.approve_patient_view,name='approve-patient'),
    path('reject-patient/<int:pk>', appointment_views.reject_patient_view,name='reject-patient'),
    path('approve-appointment/<int:pk>', appointment_views.approve_appointment_view,name='approve-appointment'),
    path('reject-appointment/<int:pk>', appointment_views.reject_appointment_view,name='reject-appointment'),
    path('delete-appointment/<int:pk>',appointment_views.delete_appointment_view,name='delete-appointment'),
]

#---------FOR COMMON URLS-------------------------------------
urlpatterns+=[
    path('',common_views.home_view,name=''),
    path('aboutus', common_views.aboutus_view),
    path('contactus', common_views.contactus_view,name="contactus"),
    path('search', common_views.search_view,name='search'),
    path('load-form/', common_views.load_form, name='load_form'),  # AJAX URL to fetch forms dynamically
    path('searchdoctor', common_views.search_doctor_view,name='searchdoctor'),
]

#---------FOR ADMIN RELATED URLS-------------------------------------
urlpatterns+=[
    path('admin-patient', admin_views.admin_patient_view,name='admin-patient'),
    path('delete-patient-from-hospital/<int:pk>', misc_views.delete_patient_from_hospital_view,name='delete-patient-from-hospital'),
    path('update-patient/<int:pk>', admin_views.update_patient_view,name='update-patient'),
    path('admin-add-patient', admin_views.admin_add_patient_view,name='admin-add-patient'),
    path('admin-appointment', admin_views.admin_appointment_view,name='admin-appointment'),
    path('admin-add-appointment', admin_views.admin_add_appointment_view,name='admin-add-appointment'),
    path('admin-dashboard', admin_views.admin_dashboard_view,name='admin-dashboard'),
    path('admin-doctor', admin_views.admin_doctor_view,name='admin-doctor'),
    path('update-doctor/<int:pk>', admin_views.update_doctor_view,name='update-doctor'),
    path('adminsignup', admin_views.admin_signup_view,name='adminsignup'),
    path('admin-notification',admin_views.admin_notification,name='admin-notification'),
    path('discharge-patient/<int:pk>', admin_views.discharge_patient_view,name='discharge-patient'),#To be Corrected
    # path('admin-discharge-patient',admin_views.admin_discharge_patient_view),
    path('delete-appointment/<int:pk>/', appointment_views.delete_appointment_doctor,name='delete-appointment-doctor'),
]

#---------FOR DOCTOR RELATED URLS-------------------------------------
urlpatterns +=[
    path('doctor-dashboard', doctor_views.doctor_dashboard_view,name='doctor-dashboard'),
    path('doctor-patient', doctor_views.doctor_patient_view,name='doctor-patient'),
    path('doctor-view-discharge-patient',doctor_views.doctor_view_discharge_patient_view,name='doctor-view-discharge-patient'),
    path('doctor-appointment', doctor_views.doctor_appointment_view,name='doctor-appointment'),
    path('doctorsignup', doctor_views.doctor_signup_view,name='doctorsignup'),
    path('doctor-availability',doctor_views.doctor_availability,name='doctor-availability'),
    path('reset-availability',doctor_views.reset_availability,name='reset-availability'),
    path('delete-appointment-doctor/<int:pk>/', appointment_views.delete_appointment,name='delete-appointment'),
    
]

#---------FOR PATIENT RELATED URLS-------------------------------------
urlpatterns +=[
    path('patient-dashboard', patient_views.patient_dashboard_view,name='patient-dashboard'),
    path('patient-appointment', patient_views.patient_appointment_view,name='patient-appointment'),
    path('patient-book-appointment', patient_views.patient_book_appointment_view,name='patient-book-appointment'),
    path('patient-view-doctor', patient_views.patient_view_doctor_view,name='patient-view-doctor'),
    path('patient-discharge', patient_views.patient_discharge_view,name='patient-discharge'),
    path('patientsignup', patient_views.patient_signup_view,name='patient-signup'),
    path('patient-fitness', patient_views.patient_fitness,name='patient-fitness'),
    path('update-userhealth',patient_views.update_userhealth,name='update-userhealth')
]


urlpatterns+=[
    path('download-pdf/<int:pk>', report_views.download_pdf_view,name='download-pdf'),
    path('get-diet/',feature_views.get_diet,name='get_diet'),
    path('api/departments/', common_views.get_departments, name='get_departments'),
    path('api/doctors/<str:specialty>/', common_views.get_doctors_by_specialty, name='get_doctors_by_specialty'),
    path('api/doctors/name/<str:selected_doc>/', common_views.get_doctor_by_name, name='get_doctor_by_name'),
    path('api/doctors/<int:doctor_id>/available_dates/', common_views.get_available_dates, name='get_available_dates'),
    path('api/doctors/by_user/<int:user_id>/available_dates/', common_views.get_available_dates_by_user, name='get-available-dates-by-user'),
    path('api/schedule_appointment/', common_views.schedule_appointment, name='schedule_appointment'),
]

hospital/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now


departments = [
    ('Cardiologist', 'Cardio'),
    ('Dermatologists', 'Derma'),
    ('Allergists', 'Allergy'),
    ('General Surgery', 'Gen Surg'),
    ('Pediatricians', 'Pedia'),
    ('Orthopedic Surgeons', 'Ortho'),
    ('Neurologists', 'Neuro'),
    ('Psychiatrists', 'Psych'),
    ('Gynecologists', 'Gynae'),
    ('Endocrinologists', 'Endo')
]


# Gender Choices (Defined Outside the Model)
GENDER_CHOICES = [
    ('Male', 'Male'),
    ('Female', 'Female'),
]

# Appointment Day Choices
DAY_CHOICES = [
    ('Sunday', 'Sunday'),
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
    ('Friday', 'Friday'),
    ('Saturday', 'Saturday'),
]



class Doctor(models.Model):
    user= models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pic/DoctorProfilePic/',null=True,blank=True)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20,null=True)
    department= models.CharField(max_length=50,choices=departments,default='Cardiologist')
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, null=True, default='Male')
    status=models.BooleanField(default=False)
    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name
    @property
    def get_id(self):
        return self.user.id
    def __str__(self):
        return "{} ({})".format(self.user.first_name,self.department)

class Patient(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic= models.ImageField(upload_to='profile_pic/PatientProfilePic/',null=True,blank=True)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20,null=False)
    symptoms = models.CharField(max_length=100,null=False)
    assignedDoctorId = models.PositiveIntegerField(null=True)
    admitDate=models.DateField(auto_now=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, null=True, blank=True)
    status=models.BooleanField(default=False)
    dob = models.DateField(null=True, blank=True)
    is_emergency = models.BooleanField(default=False)
    is_discharged = models.BooleanField(default=False)
    
    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name
    @property
    def get_id(self):
        return self.user.id
    def __str__(self):
        return self.user.first_name+" ("+self.symptoms+")"


class Appointment(models.Model):
    patientId=models.PositiveIntegerField(null=True)
    doctorId=models.PositiveIntegerField(null=True)
    patientName=models.CharField(max_length=40,null=True)
    doctorName=models.CharField(max_length=40,null=True)
    appointmentDate=models.DateField(null=False,editable=True)
    appointment_day = models.CharField(max_length=10, choices=DAY_CHOICES, null=True)
    description=models.TextField(max_length=500)
    status=models.BooleanField(default=False)



class PatientDischargeDetails(models.Model):
    patientId=models.PositiveIntegerField(null=True)
    patientName=models.CharField(max_length=40)
    assignedDoctorName=models.CharField(max_length=40)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20,null=True)
    symptoms = models.CharField(max_length=100,null=True)
    
    admitDate=models.DateField(null=False)
    releaseDate=models.DateField(null=False)
    daySpent=models.PositiveIntegerField(null=False)
    
    roomCharge=models.PositiveIntegerField(null=False)
    medicineCost=models.PositiveIntegerField(null=False)
    doctorFee=models.PositiveIntegerField(null=False)
    OtherCharge=models.PositiveIntegerField(null=False)
    total=models.PositiveIntegerField(null=False)
    
class DoctorAvailability(models.Model):
    doctor = models.ForeignKey('Doctor', on_delete=models.CASCADE)
    date_available = models.DateField(default=now) 
    day_of_week = models.CharField(max_length=10, choices=DAY_CHOICES)
    start_time = models.TimeField()
    end_time = models.TimeField()

    def __str__(self):
        return f"Availability - {self.doctor} on {self.day_of_week}"  
    

ACTIVITY_LEVELS = {
    "sedentary": 1.2,
    "light": 1.375,
    "moderate": 1.55,
    "very_active": 1.725,
    "super_active": 1.9,
}    
      

class UserHealth(models.Model):
    GOAL_CHOICES = [
        ("maintain", "Maintain Weight"),
        ("lose", "Lose Weight"),
        ("gain", "Gain Weight"),
    ]
    
    user = models.ForeignKey('Patient', on_delete=models.CASCADE, null=True)
    height = models.FloatField(null=True, blank=True)
    weight = models.FloatField(null=True, blank=True)
    activity_level = models.CharField(
        max_length=20, 
        choices=[(k, k.replace("_", " ").title()) for k in ACTIVITY_LEVELS.keys()],
        default="sedentary"
    )
    goal = models.CharField(max_length=10, choices=GOAL_CHOICES, default="maintain")

    
    def __str__(self):
        return f"UserHealth - {self.user}"

hospital/views/appointment_views.py
from django.shortcuts import render,redirect,reverse
from hospital import forms, models
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required,user_passes_test
from django.contrib.auth import logout,authenticate,login
from django.conf import settings




def is_admin(user):
    return user.groups.filter(name='ADMIN').exists()
def is_doctor(user):
    return user.groups.filter(name='DOCTOR').exists()


@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def approve_doctor_view(request,pk):
    doctor= models.Doctor.objects.get(id=pk)
    doctor.status=True
    doctor.save()
    return redirect(reverse('admin-doctor'))


@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def approve_appointment_view(request,pk):
    appointment=models.Appointment.objects.get(id=pk)
    appointment.status=True
    appointment.save()
    return redirect(reverse('admin-appointment'))

@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def approve_patient_view(request,pk):
    patient=models.Patient.objects.get(id=pk)
    patient.status=True
    patient.save()
    return redirect(reverse('admin-patient'))

@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def reject_patient_view(request,pk):
    patient=models.Patient.objects.get(id=pk)
    user=models.User.objects.get(id=patient.user_id)
    user.delete()
    patient.delete()
    return redirect('admin-patient')


@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def reject_doctor_view(request,pk):
    doctor=models.Doctor.objects.get(id=pk)
    user=models.User.objects.get(id=doctor.user_id)
    user.delete()
    doctor.delete()
    return redirect('admin-doctor')

@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def reject_appointment_view(request,pk):
    appointment=models.Appointment.objects.get(id=pk)
    appointment.delete()
    return redirect('admin-appointment')

@login_required(login_url='doctorlogin')
@user_passes_test(is_doctor)
def delete_appointment_view(request,pk):
    appointment=models.Appointment.objects.get(id=pk)
    appointment.delete()
    doctor=models.Doctor.objects.get(user_id=request.user.id) #for profile picture of doctor in sidebar
    appointments=models.Appointment.objects.all().filter(status=True,doctorId=request.user.id)
    patientid=[]
    for a in appointments:
        patientid.append(a.patientId)
    patients=models.Patient.objects.all().filter(status=True,user_id__in=patientid)
    appointments=zip(appointments,patients)
    return render(request,'hospital/doctor/doctor_appointment.html',{'appointments':appointments,'doctor':doctor})


@login_required(login_url='adminlogin')
@user_passes_test(is_admin)
def delete_appointment(request,pk):
    appointment=models.Appointment.objects.get(id=pk)
    appointment.delete()
    return redirect('admin-appointment')

@login_required(login_url='doctorlogin')
@user_passes_test(is_doctor)
def delete_appointment_doctor(request,pk):
    appointment=models.Appointment.objects.get(id=pk)
    appointment.delete()
    return redirect('doctor-appointment')

hospital/views/authentication_views.py
from django.shortcuts import render,redirect,reverse
from hospital import forms, models
from django.db.models import Sum
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required,user_passes_test
from django.contrib.auth import logout,authenticate,login
from datetime import datetime,timedelta,date
from django.conf import settings
from django.contrib import messages
from django.db.models import Q


def logout_view(request):
    logout(request)  # Logs out the user
    return redirect('')

#-----------for checking user is doctor , patient or admin
def is_admin(user):
    return user.groups.filter(name='ADMIN').exists()
def is_doctor(user):
    return user.groups.filter(name='DOCTOR').exists()
def is_patient(user):
    return user.groups.filter(name='PATIENT').exists()


def user_login(request):
    if request.method == "POST":
        loginform = forms.LoginForm(request.POST)
        if loginform.is_valid():
            username = loginform.cleaned_data["username"]
            password = loginform.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)  # Check credentials
            print()
            if user is not None:
                login(request, user)  # Log the user in
                return redirect("afterlogin")  # Redirect to some page after login
            else:
                messages.error(request,"Invalid Credentials")
                return render(request, "hospital/index.html", {"loginform": loginform})

    else:
        loginform = forms.LoginForm()
    return render(request, "hospital/index.html", {"loginform": loginform})



#---------AFTER ENTERING CREDENTIALS WE CHECK WHETHER USERNAME AND PASSWORD IS OF ADMIN,DOCTOR OR PATIENT
def afterlogin_view(request):
    if is_admin(request.user):
        return redirect('admin-dashboard')
    
    elif is_doctor(request.user):
        accountapproval=models.Doctor.objects.all().filter(user_id=request.user.id,status=True)
        if accountapproval:
            return redirect('doctor-dashboard')
        else:
            return render(request,'hospital/doctor/doctor_wait_for_approval.html',{'title': 'Wait For Approval'})
    elif is_patient(request.user):
        accountapproval=models.Patient.objects.all().filter(user_id=request.user.id,status=True)
        if accountapproval:
            return redirect('patient-dashboard')
        else:
            return render(request,'hospital/patient/patient_wait_for_approval.html')
        
        

templates/hospital/admin/admin_add_appointment.html
{% extends 'hospital/admin/admin_base.html' %}
{% load widget_tweaks %}
{% block content %}

<head>
  <style media="screen">
    a:link {
      text-decoration: none;
    }

    .note {
      text-align: center;
      height: 80px;
      background: -webkit-linear-gradient(left, #0072ff, #8811c5);
      color: #fff;
      font-weight: bold;
      line-height: 80px;
    }

    .form-content {
      padding: 5%;
      border: 1px solid #ced4da;
      margin-bottom: 2%;
    }

    .form-control {
      border-radius: 1.5rem;
    }

    .btnSubmit {
      border: none;
      border-radius: 1.5rem;
      padding: 1%;
      width: 20%;
      cursor: pointer;
      background: #0062cc;
      color: #fff;
    }

    .menu {
      top: 50px;
    }
  </style>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<br><br>
<!------ add appointment page---------->
<form method="post">
  {% csrf_token %}
  <div class="container register-form">
    <div class="form">
      <div class="note">
        <p>Book Appointment Details</p>
      </div>
      <div class="form-content">
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              {% render_field appointmentForm.description class="form-control" placeholder="Description" %}
            </div>
            <div class="form-group">
              {% render_field appointmentForm.doctorId class="form-control" placeholder="doctor" %}
            </div>
            <div class="form-group">
              {% render_field appointmentForm.patientId class="form-control" placeholder="patient" %}
            </div>

          </div>

        </div>
        <button type="submit" class="btnSubmit">Book</button>
      </div>
    </div>
  </div>
</form>



{% endblock content %}

templates/hospital/admin/admin_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>{% block title %}Admin Dashboard{% endblock title %}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <link rel="icon" type="image/x-icon" href="{% static 'images/Med.ico' %}">
  <link rel="stylesheet" href="{% static '/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/admin_style.css' %}">
  <script src="{% static 'js/time_and_date.js' %}" defer></script> <!-- Script loads after HTML parsing -->
</head>

<body>

  <!-- Header -->
  {% include 'hospital/other/header.html'%}


  <!-- Sidebar and Main Content -->
  <div class="afterlogin-wrapper font-2">
    <!-- Sidebar Navigation -->
    <nav class="menu">
      <header class="avatar">
        <img src="{% static 'images/admin.jpg' %}" alt="Admin Profile" style="width: 80px; border-radius: 50%;">
        <br>
        <h6>Admin</h6>
        <h2>{{ request.user.first_name }}</h2>
      </header>
      <ul>
        <li><a href="/admin-dashboard">Dashboard</a></li>
        <li><a href="/admin-notification">Notification</a></li>
        <li><a href="/admin-doctor">Doctor</a></li>
        <li><a href="/admin-patient">Patient</a></li>
        <li><a href="/admin-appointment">Appointment</a></li>
      </ul>
    </nav>

    <!-- Main Content -->
    <main>
      {% block content %}
      {% endblock content %}
    </main>

  </div>
  <script src="{% static 'js/search.js' %}"></script>
</body>

</html>

templates/hospital/admin/admin_patient.html
{% extends 'hospital/admin/admin_base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Admin-Patient{% endblock title %}

{% block content %}
{% include 'hospital/other/name_role_header.html' %}


<h2>Admin</h2>

<!-- Tab Navigation -->
<div class="tabs">
  <button class="tab-button active" onclick="switchTab('patients')">Patients</button>
  <button class="tab-button" onclick="switchTab('add')">Add Patient</button>
  <button class="tab-button" onclick="switchTab('approve')">Approve Patient</button>
  <button class="tab-button" onclick="switchTab('discharge')">Discharge Patient</button>
</div>

<!-- Patient List Section -->
<div id="patients" class="content show">
  <h3>Patient List</h3>
  {% if patients_approved %}
  <div class="panel panel-primary">
    <input type="text" id="Search" class="form-control mb-3" placeholder="Search Patient by name...">
    <table class="table table-hover dev-table" id="searchable_table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Profile Picture</th>
          <th>Symptoms</th>
          <th>Mobile</th>
          <th>Address</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for p in patients_approved %}
        <tr>
          <td>{{ p.get_name }}</td>
          <!-- Display patient's profile picture -->
          <td>
            {% if p.profile_pic %}
            <img src="{% static p.profile_pic.url %}" alt="Profile Picture" height="40px" width="40px">
            {% else %}
            <img src="{% static 'images/patient.jpg' %}" alt="Default Profile Picture" height="40px" width="40px">
            {% endif %}

          </td>
          <td>{{ p.symptoms }}</td>
          <td>{{ p.mobile }}</td>
          <td>{{ p.address }}</td>
          <!-- Update Patient Button -->
          <td>
            <a class="btn btn-primary btn-xs" href="#"><i class="fas fa-edit"></i></a>
            <!-- <a class="btn btn-primary btn-xs" href="{% url 'update-patient' p.id %}"><i class="fas fa-edit"></i></a> -->
          </td>
          <!-- Delete Patient Button -->
          <td><a class="btn btn-danger btn-xs" href="{% url 'delete-patient-from-hospital' p.id %}"><i
                class="fa fa-trash-o" aria-hidden="true"></i></a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
  <p class="text-center text-muted">No records found.</p>
  {% endif %}
</div>

<!-- Add Patient Section -->
<div id="add" class="content">
  <h3>Add Patient</h3>
  <form method="post" enctype="multipart/form-data" action="{% url 'admin-add-patient' %}">
    {% csrf_token %}
    <div class="container register-form">
      <div class="form">
        <div class="note">
          <p>Admit Patient To Hospital</p>
        </div>
        <div class="form-content">
          <div class="row">

            <div class="form-group">
              {% render_field userForm.first_name class="form-control" placeholder="First Name" %}
            </div>
            <div class="form-group">
              {% render_field userForm.last_name class="form-control" placeholder="Last Name" %}
            </div>
            <div class="form-group">
              {% render_field userForm.username class="form-control" placeholder="Username" %}
            </div>
            <div class="form-group">
              {% render_field patientForm.address class="form-control" placeholder="Address" %}
            </div>
            <div class="form-group">
              {% render_field userForm.email class="form-control" placeholder="email" %}
            </div>
            <div class="form-group">
              {% render_field patientForm.symptoms class="form-control" placeholder="Symptoms" %}
            </div>
            <div class="form-group">
              <label for="id_profile_pic">Profile Picture</label>
              {% render_field patientForm.profile_pic required="required" class="form-control"%}
            </div>
            <div class="form-group">
              {% render_field patientForm.dob type="date" class="form-control" placeholder="Date of Birth" %}
            </div>
            <div class="form-group">
              {% render_field patientForm.gender class="form-control" placeholder="Gender" %}
            </div>
            <div class="form-group">
              {% render_field userForm.password class="form-control" placeholder="Password" %}
            </div>
            <div class="form-group">
              {% render_field patientForm.mobile class="form-control" placeholder="Mobile" %}
            </div>
            <div class="form-group">
              {% render_field patientForm.assignedDoctorId class="form-control" placeholder="Doctor" %}
            </div>
          </div>
          <button type="submit" class="btnSubmit">Admit</button>
        </div>
      </div>
    </div>
  </form>
</div>

<!-- Approve Patient Section -->
<div id="approve" class="content">
  <h3>Approve Patients</h3>
  {% if patients_not_approved %}
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">Patients Awaiting Approval</h6>
    </div>
    <table class="table table-hover dev-table" id="searchable_table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Profile Picture</th>
          <th>Symptoms</th>
          <th>Mobile</th>
          <th>Address</th>
          <th>Approve</th>
          <th>Reject</th>
        </tr>
      </thead>
      {% for p in patients_not_approved %}
      <tr>
        <td>{{ p.get_name }}</td>
        <td>
          {% if p.profile_pic %}
          <img src="{% static p.profile_pic.url %}" alt="Profile Picture" height="40px" width="40px">
          {% else %}
          <img src="{% static 'images/patient.jpg' %}" alt="Default Profile Picture" height="40px" width="40px">
          {% endif %}
        </td>
        <td>{{ p.symptoms }}</td>
        <td>{{ p.mobile }}</td>
        <td>{{ p.address }}</td>
        <!-- Approve Patient Button -->
        <td><a class="btn btn-primary btn-xs" href="{% url 'approve-patient' p.id %}"><i
              class="fa-solid fa-check"></i></a></td>
        <!-- Reject Patient Button -->
        <td><a class="btn btn-danger btn-xs" href="{% url 'reject-patient' p.id %}"><i class="fa fa-trash-o"
              aria-hidden="true"></i></a></td>
      </tr>
      {% endfor %}
    </table>
  </div>
  {% else %}
  <p class="text-center text-muted">No records found.</p>
  {% endif %}
</div>

<!-- Discharge Patient Section -->
<div id="discharge" class="content">
  <h3>Discharge Patient</h3>
  {% if patients_approved %}
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h6 class="panel-title">Discharge Patient</h6>
    </div>
    <table class="table table-hover dev-table" id="searchable_table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Symptoms</th>
          <th>Mobile</th>
          <th>Discharge</th>
        </tr>
      </thead>
      {% for p in patients_approved %}
      <tr>
        <td> {{p.get_name}}</td>
        <td>{{p.symptoms}}</td>
        <td>{{p.mobile}}</td>
        <td><a class="btn btn-primary btn-xs" href="{% url 'discharge-patient' p.id  %}">
            <i class="fa fa-sign-in" aria-hidden="true"></i>
          </a></td>
      </tr>
      {% endfor %}
    </table>
  </div>
  {% else %}
  <p class="text-center text-muted">No records found.</p>
  {% endif %}
</div>
{% endblock content %}